### ISSUE TITLE
No such file or directory: 'requirements.txt\r'

### ISSUE THREAD

**Issue by MyProgramsForTT** [maesterzak/DjangoVercel#2]
This problem didn't happen before, but verlcel prompted this error when the project was updated today.I'm not sure how this error was made and fixed。You can help me. Thank you very much！
`<html>
<body>

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt\r'
--
22:03:56.741 |  
22:03:56.742 | [notice] A new release of pip available: 22.1.2 -> 22.2.2
22:03:56.742 | [notice] To update, run: pip install --upgrade pip
22:03:56.820 | Traceback (most recent call last):
22:03:56.821 | File "/vercel/path0/manage.py", line 5, in <module>
22:03:56.821 | import django
22:03:56.821 | ModuleNotFoundError: No module named 'django'
22:03:56.827 | Error! Command "./build_files.sh" exited with 1

</body>
</html>`
my requirtments.txt file is
`asgiref==3.5.1
sqlparse==0.4.2
tzdata==2022.1
django==4.0.5
PyMySQL==1.0.2
requests==2.26.0
django-redis==5.2.0
pytz==2022.1
constantly==15.1.0
cryptography==37.0.4
pycryptodome==3.15.0
pycryptodomex==3.15.0
gunicorn==20.0.4
`

**Comment by maesterzak** [comment]
The issue is with your requirements.txt file, 
From this error

22:03:56.827 | Error! Command "./build_files.sh" exited with 1

` my requirtments.txt file is `asgiref==3.5.1 sqlparse==0.4.2 tzdata==2022.1 django==4.0.5 PyMySQL==1.0.2 requests==2.26.0 django-redis==5.2.0 pytz==2022.1 constantly==15.1.0 cryptography==37.0.4 pycryptodome==3.15.0 pycryptodomex==3.15.0 gunicorn==20.0.4 `

You can see that you spelt requirements.txt as requirtments.txt
Fix the spelling and your program will deploy successfully.
